# -*- coding: utf-8 -*-
"""Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator."""

from nipype.interfaces.base import (CommandLine, CommandLineInputSpec, SEMLikeCommandLine, TraitedSpec,
                    File, Directory, traits, isdefined, InputMultiPath, OutputMultiPath)
import os


class BRAINSLabelStatsInputSpec(CommandLineInputSpec):
    imageVolume = File(argstr="--imageVolume %s", desc="Image Volume", exists=True)
    labelVolume = File(argstr="--labelVolume %s", desc="Label Volume", exists=True)
    labelNameFile = File(argstr="--labelNameFile %s", desc="Label Name File", exists=True)
    outputPrefixColumnNames = InputMultiPath(traits.Str, argstr="--outputPrefixColumnNames %s", desc="Prefix Column Name(s)", sep=",")
    outputPrefixColumnValues = InputMultiPath(traits.Str, argstr="--outputPrefixColumnValues %s", desc="Prefix Column Value(s)", sep=",")
    labelFileType = traits.Enum("unknown", "fslxml", "ants", "csv", argstr="--labelFileType %s", desc="Label File Type")
    numberOfHistogramBins = traits.Int(argstr="--numberOfHistogramBins %d", desc="Number Of Histogram Bins")
    minMaxType = traits.Enum("image", "label", "manual", argstr="--minMaxType %s", desc="Define minimim and maximum values based upon the image, label, or via command line")
    userDefineMinimum = traits.Float(argstr="--userDefineMinimum %f", desc="User define minimum value")
    userDefineMaximum = traits.Float(argstr="--userDefineMaximum %f", desc="User define maximum value")


class BRAINSLabelStatsOutputSpec(TraitedSpec):
    pass


class BRAINSLabelStats(SEMLikeCommandLine):
    """title: Label Statistics (BRAINS)

category: Quantification

description: Compute image statistics within each label of a label map.

version: 5.2.0

documentation-url: http://www.nitrc.org/plugins/mwiki/index.php/brains:BRAINSClassify

license: https://www.nitrc.org/svn/brains/BuildScripts/trunk/License.txt

contributor: Vincent A. Magnotta

acknowledgements: Funding for this work was provided by the Dana Foundation

"""

    input_spec = BRAINSLabelStatsInputSpec
    output_spec = BRAINSLabelStatsOutputSpec
    _cmd = " BRAINSLabelStats "
    _outputs_filenames = {}
    _redirect_x = False
